source "https://rubygems.org"

module ::Kernel
  def pg_master?
    ENV["PG_MASTER"] == '1'
  end
end

if pg_master?
  gem 'pg', github: 'ged/ruby-pg'
else
  gem 'pg', path: '/ruby-pg'
end

gem 'benchmark-ips', '~> 2.2.0'
gem 'byebug'
