source 'https://rubygems.org'

module ::Kernel
  def rails_master?
    ENV["RAILS_MASTER"] == '1'
  end
end

if rails_master?
  gem 'rails', github: 'rails'
  gem 'arel', github: 'rails/arel', branch: 'master'
else
  gem 'rails', path: '/rails'
end

gem 'ffaker'
gem 'sqlite3'
gem 'mysql2'
gem 'pg'

# Update gem version once upstream commit has been released. This is required
# for `quiet` mode in benchmark/ips.
gem 'benchmark-ips', github: 'evanphx/benchmark-ips', ref: '11d8f2071313145f246b9b5e383d282a5a0b3179'
