source 'https://rubygems.org'

gem 'rails', path: '/rails'

# uncomment this to use Rails from HEAD
# gem 'rails', github: 'rails'

gem 'ffaker'
gem 'sqlite3'
gem 'stackprof'
gem 'mysql2'
gem 'pg'
gem 'arel', github: 'rails/arel', branch: 'master'
