source 'https://rubygems.org'

module ::Kernel
  def rails_master?
    ENV["RAILS_MASTER"] == '1'
  end
end

if rails_master?
  gem 'rails', github: 'rails'
  gem 'arel', github: 'rails/arel', branch: 'master'
else
  gem 'rails', path: '/rails'
end

gem 'sqlite3', '1.3.10'
gem 'mysql2', '0.3.18'
gem 'pg', '0.18.1'
gem 'benchmark-ips', '~> 2.2.0'
